### ISSUE TITLE
Unexpected identifier on "await dbUtil.database('mydatabase');"

### ISSUE THREAD

**Issue by lumberbeard** [spatney/documentdb-util#1]
Hi, just wondering if anyone knows what's wrong here?  

With simply the following it's failing with 'Unexpected identifier' on the dbUtil object.  I tested on node version 8.9 and 8.9.1 with documentdb and documentdb-util installed.

```
var DocumentDbUtility = require("documentdb-util");
var dbUtil = new DocumentDbUtility({authKey: 'xxx' host: 'xxx'});
let database = await dbUtil.database('newzible-test');
                     ^^^^^
```

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)

**Comment by lumberbeard** [comment]
I'm a fool.  I forgot the async function, sigh.  Sorry!
